AWSTemplateFormatVersion: 2010-09-09
Description: QuakeNet event detail grabbing stack

Parameters:
  DeploymentBucketName:
    Description: The deployment bucket
    Type: String
  RolePermissionsBoundary:
    Description: An optional permissions boundary to associate with roles
    Type: String
  EventDetailsGrabberLambdaMemorySize:
    Description: The amount of memory for the event detail grabber lambda
    Type: Number
  EventDetailsGrabberLambdaTimeout:
    Description: The timeout in seconds for the event detail grabber lambda
    Type: Number
  EventDetailsGrabberLambdaConcurrency:
    Description: The maximum number of instances to create when processing queues
    Type: Number
    MinValue: 1
  UsgsEventDetailsQueryCompleteTopicArn:
    Type: String
  UsgsEventDetailsQueryQueueArn:
    Type: String
  QuakeNetSourceBucketName:
    Type: String
  HttpRequestTimeoutMs:
    Description: The request timeout in milliseconds for HTTP requests
    Type: Number
  HttpConnectionTimeoutMs:
    Description: The connection timeout in milliseconds for HTTP requests
    Type: Number
  Version:
    Description: The build version
    Type: String


Conditions:
  HasRolePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - ""
          - !Ref RolePermissionsBoundary

Resources:
  EventDetailsGrabberLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary:
        Fn::If:
          - HasRolePermissionsBoundary
          - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${RolePermissionsBoundary}
          - !Ref AWS::NoValue
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Logging
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:logs:*:*:*
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
        - PolicyName: SQS
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !Ref UsgsEventDetailsQueryQueueArn
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
        - PolicyName: SNS
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !Ref UsgsEventDetailsQueryCompleteTopicArn
                Action:
                  - sns:Publish
        - PolicyName: S3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:s3:::${QuakeNetSourceBucketName}/*
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
              - Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:s3:::${QuakeNetSourceBucketName}
                Action:
                  - s3:ListBucket



  EventDetailsGrabberLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Queries USGS for earthquake event details by ID
      Code:
        S3Bucket: !Ref DeploymentBucketName
        S3Key: !Sub lambda/quake-net-event-details-grabber-${Version}-lambda.zip
      Handler: edu.colorado.cires.mgg.quakenet.lambda.eventdetailsgrabber.EventDetailsGrabberLambda::handleRequest
      Runtime: java11
      MemorySize: !Ref EventDetailsGrabberLambdaMemorySize
      Timeout: !Ref EventDetailsGrabberLambdaTimeout
      ReservedConcurrentExecutions: !Ref EventDetailsGrabberLambdaConcurrency
      Role: !GetAtt EventDetailsGrabberLambdaRole.Arn
      Environment:
        Variables:
          CONNECTION_TIMEOUT_MS: !Ref HttpConnectionTimeoutMs
          REQUEST_TIMEOUT_MS: !Ref HttpRequestTimeoutMs
          TOPIC_ARN: !Ref UsgsEventDetailsQueryCompleteTopicArn
          DOWNLOAD_BUCKET: !Ref QuakeNetSourceBucketName



  EventDetailsGrabberLambdaQueueTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      Enabled: true
      EventSourceArn: !Ref UsgsEventDetailsQueryQueueArn
      FunctionName: !GetAtt EventDetailsGrabberLambda.Arn