AWSTemplateFormatVersion: 2010-09-09
Description: QuakeNet Queues

Parameters:
  StackPrefix:
    Type: String
  VisibilityTimeoutSeconds:
    Description: The timeout in seconds to keep in-flight messages hidden
    Type: Number
  MessageMaxReceiveCount:
    Description: The number of times a message can be received in a queue before sending to the DLQ
    Type: Number

Resources:

  InitiatorCompleteTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${StackPrefix}-${AWS::AccountId}-initiator

  UsgsDateQueryCompleteTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${StackPrefix}-${AWS::AccountId}-usgs-date-query

  UsgsEventDetailsQueryCompleteTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${StackPrefix}-${AWS::AccountId}-usgs-event-detail-query

  ReportInitiatorCompleteTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${StackPrefix}-${AWS::AccountId}-report-initiator

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${StackPrefix}-${AWS::AccountId}-dlq

  UsgsDateQueryQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: !Ref VisibilityTimeoutSeconds
      QueueName: !Sub ${StackPrefix}-${AWS::AccountId}-usgs-date-query
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: !Ref MessageMaxReceiveCount

  UsgsEventDetailsQueryQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: !Ref VisibilityTimeoutSeconds
      QueueName: !Sub ${StackPrefix}-${AWS::AccountId}-usgs-event-details-query
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: !Ref MessageMaxReceiveCount

  ReportInitiatorQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: !Ref VisibilityTimeoutSeconds
      QueueName: !Sub ${StackPrefix}-${AWS::AccountId}-report-initiatior
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: !Ref MessageMaxReceiveCount

  ReportGenerationQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: !Ref VisibilityTimeoutSeconds
      QueueName: !Sub ${StackPrefix}-${AWS::AccountId}-report-generation
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: !Ref MessageMaxReceiveCount

  UsgsDateQueryCompleteTopicToUsgsEventDetailsQueryQueue:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref UsgsEventDetailsQueryQueue
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublishToTopic
            Resource: !GetAtt UsgsEventDetailsQueryQueue.Arn
            Effect: Allow
            Principal:
              Service:
                - sns.amazonaws.com
            Action:
              - sqs:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref UsgsDateQueryCompleteTopic

  InitiatorCompleteTopicToUsgsDateQueryQueue:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref UsgsDateQueryQueue
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublishToTopic
            Resource: !GetAtt UsgsDateQueryQueue.Arn
            Effect: Allow
            Principal:
              Service:
                - sns.amazonaws.com
            Action:
              - sqs:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref InitiatorCompleteTopic

  UsgsEventDetailsQueryCompleteTopicToReportInitiatorQueue:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ReportInitiatorQueue
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublishToTopic
            Resource: !GetAtt ReportInitiatorQueue.Arn
            Effect: Allow
            Principal:
              Service:
                - sns.amazonaws.com
            Action:
              - sqs:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref UsgsEventDetailsQueryCompleteTopic

  ReportInitiatorCompleteTopicToReportGenerationQueue:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ReportInitiatorQueue
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublishToTopic
            Resource: !GetAtt ReportGenerationQueue.Arn
            Effect: Allow
            Principal:
              Service:
                - sns.amazonaws.com
            Action:
              - sqs:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref ReportInitiatorCompleteTopic


Outputs:
  InitiatorCompleteTopicArn:
    Value: !Ref InitiatorCompleteTopic
  UsgsDateQueryCompleteTopicArn:
    Value: !Ref UsgsDateQueryCompleteTopic
  UsgsEventDetailsQueryCompleteTopicArn:
    Value: !Ref UsgsEventDetailsQueryCompleteTopic
  ReportInitiatorCompleteTopicArn:
    Value: !Ref ReportInitiatorCompleteTopic
  UsgsDateQueryQueueUrl:
    Value: !Ref UsgsDateQueryQueue
  UsgsDateQueryQueueArn:
    Value: !GetAtt UsgsDateQueryQueue.Arn
  UsgsEventDetailsQueryQueueUrl:
    Value: !Ref UsgsEventDetailsQueryQueue
  UsgsEventDetailsQueryQueueArn:
    Value: !GetAtt UsgsEventDetailsQueryQueue.Arn
  ReportInitiatorQueueUrl:
    Value: !Ref ReportInitiatorQueue
  ReportInitiatorQueueArn:
    Value: !GetAtt ReportInitiatorQueue.Arn
  ReportGenerationQueueUrl:
    Value: !Ref ReportGenerationQueue
  ReportGenerationQueueArn:
    Value: !GetAtt ReportGenerationQueue.Arn