AWSTemplateFormatVersion: 2010-09-09
Description: QuakeNet Queues


Resources:

  UsgsQueryTopic:
    Type: AWS::SNS::Topic

  UsgsQueryQueue:
    Type: AWS::SQS::Queue


  UsgsQueryTopicToUsgsQueryQueue:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref UsgsQueryQueue
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublishToTopic
            Resource: !GetAtt UsgsQueryQueue.Arn
            Effect: Allow
            Principal:
              Service:
                - sns.amazonaws.com
            Action:
              - sqs:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref UsgsQueryTopic


Outputs:
  UsgsQueryTopicArn:
    Value: !Ref UsgsQueryTopic

  UsgsQueryQueueUrl:
    Value: !Ref UsgsQueryQueue
  UsgsQueryQueueArn:
    Value: !GetAtt UsgsQueryQueue.Arn