version: 0.2

env:
  parameter-store:
    gpg_key: gpg_key
    gpg_key_id: gpg_key_id
    gpg_key_pw: gpg_key_pw
    github_pat: github_pat
    github_username: github_username

phases:
  pre_build:
    commands:
      - echo "$gpg_key" | base64 -d > /tmp/gpg.key
      - git config --global user.email "mggdev-aws@mggdev.cloud"
      - git config --global user.name "mggdev-aws"
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn -B install -Pdep-check
      - chmod +x quake-net-build/target/codepipeline/buildspec-release.sh
      - quake-net-build/target/codepipeline/buildspec-release.sh "$gpg_key" "$gpg_key_id" "$gpg_key_pw" "$github_pat" "$github_username"
artifacts:
  files:
    - '**/*'
