AWSTemplateFormatVersion: 2010-09-09
Description: Trackline Ingest Stack

Parameters:
  StackPrefix:
    Description: A prefix that identifies this stack
    Type: String
  RolePermissionsBoundary:
    Description: An optional permissions boundary to associate with roles
    Type: String
    Default: ""
  LogRetentionInDays:
    Description: The number of days to keep CloudWatch logs
    Type: Number
    MinValue: 0
    Default: 30
  InitiatorLambdaMemorySize:
    Description: The amount of memory for the initiator lambda
    Type: Number
    MinValue: 256
    Default: 1024
  InitiatorLambdaTimeout:
    Description: The timeout in seconds for the initiator lambda
    Type: Number
    MinValue: 10
    MaxValue: 900
    Default: 120
  InitiatorCronExpression:
    Description: The EventBridge Schedule Expression to check for new event data
    Type: String
    Default: 'cron(0 1 * * ? *)'
  DefaultStartDate:
    Description: The earliest date to check for events when initializing the earthquake data set
    Default: '1660-01-01'
    Type: String
  HttpRequestTimeoutMs:
    Description: The request timeout in milliseconds for HTTP requests
    Type: Number
    Default: 300000
  HttpConnectionTimeoutMs:
    Description: The connection timeout in milliseconds for HTTP requests
    Type: Number
    Default: 30000
  QueueMessageVisibilityTimeoutSeconds:
    Description: The timeout in seconds to keep in-flight messages hidden
    Type: Number
    Default: 900
  QueueMessageMaxReceiveCount:
    Description: The number of times a message can be received in a queue before sending to the DLQ
    Type: Number
    Default: 3
  EventGrabberLambdaMemorySize:
    Description: The amount of memory for the event grabber lambda
    Type: Number
    MinValue: 256
    Default: 1024
  EventGrabberLambdaConcurrency:
    Description: The maximum number of instances to create when processing queues
    Type: Number
    MinValue: 1
    Default: 10
  EventGrabberLambdaTimeout:
    Description: The timeout in seconds for the event grabber lambda
    Type: Number
    MinValue: 10
    MaxValue: 900
    Default: 480
  EventGrabberLambdaPageSize:
    Description: The number of quake events to query at a time
    Type: Number
    Default: 200
  EventDetailsGrabberLambdaMemorySize:
    Description: The amount of memory for the event details grabber lambda
    Type: Number
    MinValue: 256
    Default: 1024
  EventDetailsGrabberLambdaConcurrency:
    Description: The maximum number of instances of the event details grabber lambda
    Type: Number
    MinValue: 1
    Default: 10
  EventDetailsGrabberLambdaTimeout:
    Description: The timeout in seconds for the event details grabber lambda
    Type: Number
    MinValue: 10
    MaxValue: 900
    Default: 480
  ReportInitiatorLambdaMemorySize:
    Description: The amount of memory for the report initiator lambda
    Type: Number
    MinValue: 256
    Default: 1024
  ReportInitiatorLambdaConcurrency:
    Description: The maximum number of instances of the report initiatorlambda
    Type: Number
    MinValue: 1
    Default: 10
  ReportInitiatorLambdaTimeout:
    Description: The timeout in seconds for the report initiator lambda
    Type: Number
    MinValue: 10
    MaxValue: 900
    Default: 480



Resources:

  BucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        StackPrefix: !Ref StackPrefix
        EnvironmentType:
          Fn::ImportValue: !Sub ${StackPrefix}-quake-net-environment-type
        RolePermissionsBoundary: !Ref RolePermissionsBoundary
        DeploymentBucketName:
          Fn::ImportValue: !Sub ${StackPrefix}-quake-net-deployment-bucket
        Version: @project.version@@dashTimestamp@
      TemplateURL:
        Fn::Sub:
          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/bucket-stack.yaml
          - DeploymentBucketName:
              Fn::ImportValue: !Sub ${StackPrefix}-quake-net-deployment-bucket


  MessagingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        StackPrefix: !Ref StackPrefix
        VisibilityTimeoutSeconds: !Ref QueueMessageVisibilityTimeoutSeconds
        MessageMaxReceiveCount: !Ref QueueMessageMaxReceiveCount
      TemplateURL:
        Fn::Sub:
          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/messaging-stack.yaml
          - DeploymentBucketName:
              Fn::ImportValue: !Sub ${StackPrefix}-quake-net-deployment-bucket

  InitiatorStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DeploymentBucketName:
          Fn::ImportValue: !Sub ${StackPrefix}-quake-net-deployment-bucket
        RolePermissionsBoundary: !Ref RolePermissionsBoundary
        InitiatorLambdaMemorySize: !Ref InitiatorLambdaMemorySize
        InitiatorLambdaTimeout: !Ref InitiatorLambdaTimeout
        InitiatorCronExpression: !Ref InitiatorCronExpression
        DefaultStartDate: !Ref DefaultStartDate
        InitiatorCompleteTopicArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.InitiatorCompleteTopicArn
        QuakeNetSourceBucketName:
          Fn::GetAtt:
            - BucketStack
            - Outputs.QuakeNetSourceBucketName
        HttpRequestTimeoutMs: !Ref HttpRequestTimeoutMs
        HttpConnectionTimeoutMs: !Ref HttpConnectionTimeoutMs
        Version: @project.version@@dashTimestamp@
      TemplateURL:
        Fn::Sub:
          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/initiator-stack.yaml
          - DeploymentBucketName:
              Fn::ImportValue: !Sub ${StackPrefix}-quake-net-deployment-bucket

  EventGrabberStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DeploymentBucketName:
          Fn::ImportValue: !Sub ${StackPrefix}-quake-net-deployment-bucket
        RolePermissionsBoundary: !Ref RolePermissionsBoundary
        EventGrabberLambdaMemorySize: !Ref EventGrabberLambdaMemorySize
        EventGrabberLambdaTimeout: !Ref EventGrabberLambdaTimeout
        EventGrabberLambdaConcurrency: !Ref EventGrabberLambdaConcurrency
        UsgsDateQueryCompleteTopicArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.UsgsDateQueryCompleteTopicArn
        UsgsDateQueryQueueArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.UsgsDateQueryQueueArn
        QuakeNetSourceBucketName:
          Fn::GetAtt:
            - BucketStack
            - Outputs.QuakeNetSourceBucketName
        HttpRequestTimeoutMs: !Ref HttpRequestTimeoutMs
        HttpConnectionTimeoutMs: !Ref HttpConnectionTimeoutMs
        Version: @project.version@@dashTimestamp@
        EventGrabberLambdaPageSize: !Ref EventGrabberLambdaPageSize
      TemplateURL:
        Fn::Sub:
          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/event-grabber-stack.yaml
          - DeploymentBucketName:
              Fn::ImportValue: !Sub ${StackPrefix}-quake-net-deployment-bucket

  EventDetailsGrabberStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DeploymentBucketName:
          Fn::ImportValue: !Sub ${StackPrefix}-quake-net-deployment-bucket
        RolePermissionsBoundary: !Ref RolePermissionsBoundary
        EventDetailsGrabberLambdaMemorySize: !Ref EventDetailsGrabberLambdaMemorySize
        EventDetailsGrabberLambdaTimeout: !Ref EventDetailsGrabberLambdaTimeout
        EventDetailsGrabberLambdaConcurrency: !Ref EventDetailsGrabberLambdaConcurrency
        UsgsEventDetailsQueryCompleteTopicArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.UsgsEventDetailsQueryCompleteTopicArn
        UsgsEventDetailsQueryQueueArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.UsgsEventDetailsQueryQueueArn
        QuakeNetSourceBucketName:
          Fn::GetAtt:
            - BucketStack
            - Outputs.QuakeNetSourceBucketName
        HttpRequestTimeoutMs: !Ref HttpRequestTimeoutMs
        HttpConnectionTimeoutMs: !Ref HttpConnectionTimeoutMs
        Version: @project.version@@dashTimestamp@
      TemplateURL:
        Fn::Sub:
          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/event-details-grabber-stack.yaml
          - DeploymentBucketName:
              Fn::ImportValue: !Sub ${StackPrefix}-quake-net-deployment-bucket

  ReportInitiatorStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DeploymentBucketName:
          Fn::ImportValue: !Sub ${StackPrefix}-quake-net-deployment-bucket
        RolePermissionsBoundary: !Ref RolePermissionsBoundary
        ReportInitiatorLambdaMemorySize: !Ref ReportInitiatorLambdaMemorySize
        ReportInitiatorLambdaTimeout: !Ref ReportInitiatorLambdaTimeout
        ReportInitiatorLambdaConcurrency: !Ref ReportInitiatorLambdaConcurrency
        ReportInitiatorCompleteTopicArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.ReportInitiatorCompleteTopicArn
        ReportInitiatorQueueArn:
          Fn::GetAtt:
            - MessagingStack
            - Outputs.ReportInitiatorQueueArn
        QuakeNetSourceBucketName:
          Fn::GetAtt:
            - BucketStack
            - Outputs.QuakeNetSourceBucketName
        Version: @project.version@@dashTimestamp@
      TemplateURL:
        Fn::Sub:
          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/report-initiator-stack.yaml
          - DeploymentBucketName:
              Fn::ImportValue: !Sub ${StackPrefix}-quake-net-deployment-bucket


