AWSTemplateFormatVersion: 2010-09-09
Description: Sets up AWS resources used to deploy QuakeNet

Parameters:
  StackPrefix:
    Description: A prefix that identifies this stack
    Type: String
  DeploymentBucketName:
    Description: The bucket used to deploy cloudformation resources
    Type: String

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DeploymentBucketName


Outputs:
  DeploymentBucketOutput:
    Description: The bucket used to deploy cloudformation resources
    Value: !Ref DeploymentBucketName
    Export:
      Name: !Sub ${StackPrefix}-quake-net-deployment-bucket

